### PR TITLE
feat: coverage for failed value computation

### PR DESCRIPTION
**Pull request by nimatrueway**
This simple use-case did not work

```
odelay.Delay(duration) { throw new TimeoutException() }.future
```

_(if there were tests already in the repo I would have added one.)_

### CODE REVIEW

**Comment by adamw** [comment]
Thanks - I think the tests are here? https://github.com/softwaremill/odelay/blob/master/odelay-testing/src/test/scalajvm/TimerSpec.scala

**Comment by adamw** [comment]
There are some test failures

**Comment by nimatrueway** [comment]
> There are some test failures

Sorry Adam, I fiddled with the tests a bit but didn't manage to fix it in 1hr. I have been hacking Scala for 7 years now but have never went through the pains of working on ScalaJS (like `Future` not having `transformWith` or not being about to match on types (e.g. `case _: Assertion =>`). I'm afraid learning it is not that useful either. I'll leave this to anyone who's interested to fix.

**Comment by adamw** [comment]
@nimatrueway I think it's simply time to drop Scala 2.11 support :)

**Pull request merged**
